### ISSUE TITLE
Add font-weight to body of css files

### ISSUE THREAD

**Issue by subnut** [caderek/aoc2022#1]
The default body-weight of aoc2024 is 300, which doesn't match  
the font that's being downloaded by the custom css (which is  
of weight 500), due to which the text looks terrible.

Please add
```css
body {
    font-weight: 500;
}
```
to both the custom css files
